"""
io_utils.py
-----------
Utilities for loading nanoparticle trajectory data generated by Langevin
dynamics simulations. Handles filename parsing, single-trajectory loading
with PBC-corrected displacement, and batch loading of all 160 trajectories.
"""

import re
from pathlib import Path

import numpy as np
import pandas as pd
from tqdm import tqdm

# Canonical data directory: two levels up from this file, then into data/
DATA_DIR = Path(__file__).resolve().parents[1].parent / 'data'

# Simulation box side length in sigma units
BOX_SIZE = 50.0


def parse_filename(filename: str) -> tuple:
    """Parse a trajectory filename into its physical parameters.

    Expected format: traj_conc{c}_charge{q}_run{r}.csv
    Decimal points are encoded as 'p', so 0p30 means 0.30.

    Parameters
    ----------
    filename : str
        Bare filename or full path string.

    Returns
    -------
    tuple of (float, float, int)
        (concentration, charge, run_id)

    Raises
    ------
    ValueError
        If the filename does not match the expected pattern.
    """
    # Strip directory components so we match on the basename only
    basename = Path(filename).name
    pattern = r'traj_conc(\d+p\d+)_charge(\d+p\d+)_run(\d+)\.csv'
    match = re.match(pattern, basename)
    if match is None:
        raise ValueError(
            f"Filename '{basename}' does not match the expected pattern "
            f"'traj_conc{{c}}_charge{{q}}_run{{r}}.csv'. "
            f"Decimal points must be encoded as 'p' (e.g. 0p30 for 0.30)."
        )
    conc_str, charge_str, run_str = match.groups()
    conc   = float(conc_str.replace('p', '.'))
    charge = float(charge_str.replace('p', '.'))
    run_id = int(run_str)
    return conc, charge, run_id


def _pbc_diff(dx: np.ndarray, box: float = BOX_SIZE) -> np.ndarray:
    """Apply minimum-image convention to a displacement array.

    For each component, if |dx| > box/2 the particle has crossed a
    periodic boundary, so we subtract box * sign(dx) to recover the
    true shortest displacement.
    """
    dx = dx.copy()
    dx[dx >  box / 2] -= box
    dx[dx < -box / 2] += box
    return dx


def load_trajectory(filepath) -> pd.DataFrame:
    """Load a single trajectory CSV and compute derived per-step quantities.

    Adds two columns to the raw data:
      - 'displacement': frame-to-frame displacement magnitude, PBC-corrected.
        For step 0 this is set to NaN (no previous frame).
      - 't_index': integer frame index starting from 0.

    The periodic boundary correction uses the minimum-image convention with
    box size 50 sigma. Without this correction, a particle crossing a box
    face would produce a spurious displacement of ~50 sigma.

    Parameters
    ----------
    filepath : str or Path
        Path to the trajectory CSV file.

    Returns
    -------
    pd.DataFrame
        DataFrame with columns: step, t, x, y, z, vx, vy, vz,
        displacement, t_index.
    """
    df = pd.read_csv(filepath)
    df = df.reset_index(drop=True)
    df['t_index'] = np.arange(len(df), dtype=int)

    # Frame-to-frame displacements, PBC-corrected
    dx = _pbc_diff(df['x'].diff().to_numpy())
    dy = _pbc_diff(df['y'].diff().to_numpy())
    dz = _pbc_diff(df['z'].diff().to_numpy())
    df['displacement'] = np.sqrt(dx**2 + dy**2 + dz**2)
    # First frame has no predecessor
    df.loc[0, 'displacement'] = np.nan

    return df


def load_all_trajectories(data_dir=None) -> tuple:
    """Load all 160 trajectories and the accompanying metadata.

    Parameters
    ----------
    data_dir : str or Path, optional
        Directory containing the CSV files. Defaults to DATA_DIR.

    Returns
    -------
    trajs : dict
        Mapping (conc, charge, run_id) -> pd.DataFrame.
    meta : pd.DataFrame
        Contents of metadata.csv.
    """
    if data_dir is None:
        data_dir = DATA_DIR
    data_dir = Path(data_dir)

    # Collect all trajectory files
    csv_files = sorted(data_dir.glob('traj_*.csv'))

    trajs = {}
    for fp in tqdm(csv_files, desc='Loading trajectories', unit='file'):
        try:
            conc, charge, run_id = parse_filename(fp.name)
        except ValueError as err:
            print(f'  Skipping {fp.name}: {err}')
            continue
        trajs[(conc, charge, run_id)] = load_trajectory(fp)

    meta = pd.read_csv(data_dir / 'metadata.csv')

    n_conditions = len({(c, q) for c, q, _ in trajs})
    print(f'Loaded {len(trajs)} trajectories across {n_conditions} conditions.')

    return trajs, meta
